[build]
  functions = "netlify/functions"
  publish = "frontend" # or wherever your frontend files are located

[functions]
  node_bundler = "esbuild" # Use esbuild for bundling, or "webpack" if preferred
